[package]
name = "mii-labs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.20.1"
env_logger = "0.10.0"
gl = "0.14.0"
glfw = "0.49.1"
logger = "0.4.0"
thiserror = "1.0.38"
